spring.application.name=demo-backend

# ??Docker Compose????
spring.docker.compose.enabled=true

# PostgreSQL ??
spring.datasource.url=jdbc:postgresql://localhost:15432/expense_sharing_app
spring.datasource.username=myapp_user
spring.datasource.password=myapp_password
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis??????
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.xdw.demobackend.model
